// Code generated by GoHT - DO NOT EDIT.
// https://github.com/stackus/goht

package view

import "context"
import "io"
import "github.com/stackus/goht"

type httpError interface {
	Status() string
	Error() string
}

/*
	<style>
		html,
		body {
			height: 100%;
			margin: 0;
		}

		.main {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
		}

		.error {
			padding: 1em;
			margin: 1em;
			border-radius: 0.5em;
		}

		.title {
			font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
			font-size: 8em;
			color: rgb(137, 3, 3);
		}

		.message {
			font-family: 'Courier New', Courier, monospace;
			font-size: 1.5em;
			color: #333;
		}
	</style>
*/

func Error(err httpError) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		__var1 := goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
			__buf, __isBuf := __w.(goht.Buffer)
			if !__isBuf {
				__buf = goht.GetBuffer()
				defer goht.ReleaseBuffer(__buf)
			}
			if _, __err = __buf.WriteString("<main class=\"main\">\n<div class=\"error\">\n<h1 class=\"title\">Error "); __err != nil {
				return
			}
			var __var2 string
			if __var2, __err = goht.CaptureErrors(goht.EscapeString(err.Status())); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var2); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</h1>\n<hr><p class=\"message\">"); __err != nil {
				return
			}
			var __var3 string
			if __var3, __err = goht.CaptureErrors(goht.EscapeString(err.Error())); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var3); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</p>\n</div>\n</main>\n"); __err != nil {
				return
			}
			if !__isBuf {
				_, __err = io.Copy(__w, __buf)
			}
			return
		})
		if __err = Layout(err.Status()).Render(goht.PushChildren(ctx, __var1), __buf); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
